In [ ]:
'''
合并的接口有:concat(现有维度上连接),stack(创造一个新的维度来连接)
'''

In [3]:
import tensorflow as tf 
a = tf.ones([4, 35, 8]) 
b = tf.ones([2, 35, 8])

In [2]:
#合并a 和 b, concat要求除axis后面的维度以外都相等
c = tf.concat([a, b], axis=0)

In [3]:
c.shape

TensorShape([6, 35, 8])

In [5]:
a = tf.ones([4, 32, 8])
b = tf.ones([4, 3, 8])
c = tf.concat([a, b], axis=1)

In [7]:
print(c.shape)

(4, 35, 8)


In [8]:
a = tf.ones([4, 35, 8])
b = tf.ones([4, 35, 8])

In [9]:
#stack增加新维度， 要求所有的维度均相等
tf.stack([a, b], axis=0)

<tf.Tensor: shape=(2, 4, 35, 8), dtype=float32, numpy=
array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
   

In [10]:
tf.stack([a, b], axis=3)

<tf.Tensor: shape=(4, 35, 8, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        ...,

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],


In [11]:
'''
分割使用的API有：unstack（直接等分成1/axis）， split（更加自由，可以指定分割的份数和分割比例）
'''

'\n分割使用的API有：unstack\n'

In [4]:
c = tf.random.normal([2, 4, 35, 8])

In [5]:
a ,b = tf.unstack(c, axis=0)

In [6]:
print(a.shape, b.shape)

(4, 35, 8) (4, 35, 8)


In [7]:
res = tf.unstack(c, axis=3)

In [8]:
res[0].shape, res[7].shape

(TensorShape([2, 4, 35]), TensorShape([2, 4, 35]))

In [9]:
#split接口
res = tf.split(c, num_or_size_splits=2)#登分成两份
print(res[0].shape, res[1].shape)

(1, 4, 35, 8) (1, 4, 35, 8)


In [10]:
res = tf.split(c, axis = 3, num_or_size_splits=[1,1,3,3])

In [11]:
print(res[1].shape, res[3].shape)

(2, 4, 35, 1) (2, 4, 35, 3)
