In [1]:
import tensorflow as tf 
a = tf.ones([2,2])

In [4]:
#求解2范数，norm默认为2范数
tf.norm(a) #各元素的平方和，

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [5]:
#1范数
tf.norm(a, ord = 1)

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [6]:
#在1维度求解1范数
tf.norm(a, ord = 1, axis =1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>

In [7]:
tf.norm(a, ord = 1, axis = 0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>

In [8]:
#reduce_min/max/mean (默认情况：整个数组下的求解，也可以指定维度))
a = tf.constant([[1, 2], [3, 4]])

In [9]:
tf.reduce_min(a, axis=0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [10]:
tf.reduce_min(a, axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

In [11]:
tf.reduce_mean(a)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [12]:
a = tf.constant([[1,2,3],[4,5,6,],[7,8,9]])

In [13]:
#最大值最小值的索引argmax， argmin
tf.argmax(a)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 2, 2])>

In [14]:
tf.argmin(a)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 0, 0])>

In [21]:
tf.argmax(tf.argmax(a))

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [24]:
tf.reduce_sum(a)

<tf.Tensor: shape=(), dtype=int32, numpy=45>

In [26]:
import numpy as np 
a = np.array(a)
a.max()

9